### PR TITLE
Add JetBrains Rider IDE

### PR DESCRIPTION
**Pull request by maartenba**
This PR adds [JetBrains Rider](https://www.jetbrains.com/rider) as a tool, as per conversation between @hhariri and @forki [on Twitter](https://twitter.com/hhariri/status/872042404819415041).

Added Rider to:
* http://fsharp.org/use/mac/
* http://fsharp.org/use/linux/
* http://fsharp.org/use/windows/
* http://fsharp.org/use/android/
* http://fsharp.org/use/ios/

Since [Projects](http://fsharp.org/community/projects/) seems to only list community projects, I did not add Rider there. Would it make sense to add a "Commercial Editors" category?

### CODE REVIEW

**Comment by maartenba** [comment]
Shall I create one in a separate PR?

**Comment by forki** [comment]
I have no rights here. Was just an idea

2017-06-07 9:02 GMT+02:00 Maarten Balliauw <notifications@github.com>:

**Comment by dsyme** [comment]
This looks reasonable.    Documenting editor choices is a little tricky - some editors are just editors, some are full IDEs with templates etc.    But this seems a reasonable approach.  We may have to rejig things later

**Comment by ReedCopsey** [comment]
Thank you for this!  I think we should wait and hold off on a separate editor/ide page for now. We are looking at trying to reorganize currently. This gets Rider onto the main pages where people are going to find IDEs in current site, though, which is great.

**Comment by maartenba** [comment]
Cool. Thanks all!

**Pull request merged**
