### PR TITLE
fix redirects, more info

### PR DESCRIPTION
**Pull request by jackfoxy**
1) Fixes redirect_from on learning.md page
2) adds new redirect
3) adds the new Visual F# Dev Portal
4) some more info

addresses https://github.com/fsharp/fsfoundation/issues/558#issuecomment-221645760

### CODE REVIEW

**Comment by ReedCopsey** [comment]
Should this be /learn.md with a redirect_from about/learn added? (As suggested by @dsyme in #558 )

**Comment by jackfoxy** [comment]
I thought the suggestion was /learn would redirect to about/learn...but I'm agnostic

**Comment by jackfoxy** [comment]
@ReedCopsey have another look. Moved about/learning to learn and redirect from old page.

**Comment by ReedCopsey** [comment]
Looks good here - @dsyme : Was this what you were thinking?

**Comment by dsyme** [comment]
I'll merge and double check it works

**Pull request merged**
