### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by dsyme**
COsmetic updates to http://fsharp.org/use/linux

### CODE REVIEW

**Comment by dsyme** [comment]
@jschiefer please do a post-hoc review?

**Comment by jschiefer** [comment]
Looks good! Just two minor observations:
* You took out the repeated "Once installed, see..." sections and added a pointer at the top, which is good. You did not remove it from the "Install from source" section, line 105. Don't know whether that was intentional or not.
* The section on editors partially replicates [the editor section in the cross-platform page](http://fsharp.org/guides/mac-linux-cross-platform/#editing). Does this deserve a forward reference, or de-duplication?

**Comment by dsyme** [comment]
> You took out the repeated "Once installed, see..." sections and added a pointer at the top, which is good. You did not remove it from the "Install from source" section, line 105. Don't know whether that was intentional or not.


Thanks, will remove it there too

>The section on editors partially replicates the editor section in the cross-platform page. Does this deserve a forward reference, or de-duplication?

Since that covers more editors I think the duplication is OK

If you'd like to update or simplify the cross-platform guide as well, that would be great :)  It would be useful to get page view stats too to see if people are finding it and using it

**Comment by jschiefer** [comment]
The cross-platform guide is quite a hodgepodge of things. To be honest, I am not sure what exactly the page is trying to accomplish, it seems to be a generic holding pen for anything "non-Windows". Maybe a structure could be something like
* Where F# shines for writing platform-independent code (e.g. OS-independent binding to native libraries with P/Invoke)
* How to write platform-independent code (paths, EOL conventions, etc.)
* How to set up a consistent development and build environments for multiple different OSs (Mono + Ionide, or netcore + mono + Ionide for the more adventurous)
* Rough edges on each platform (not sure whether this belongs in a cross-platform guide at all).

Big changes like this should have some community discussion, at least for the broad structure, IMHO.

Allow me to climb on my soap box for a moment. I have observed that many long-time .NET users inside and outside of Microsoft use "cross-platform" or "xplat" as a synonym for "not Windows". Something about this rubs me the wrong way, maybe because in so many other platforms (e.g. Javascript, JVM), being cross-platform is the baseline, and not something exotic. Maybe this will go away over time, but we ought to try and use terms in ways that people outside the .NET echo chambers can relate to.

**Comment by dsyme** [comment]
>  it seems to be a generic holding pen for anything "non-Windows".

Yep

> Something about this rubs me the wrong way, maybe because in so many other platforms (e.g. Javascript, JVM), being cross-platform is the baseline, and not something exotic. 

I totally agree (and I collated the guide originally).  We need to totally change our approach to eliminate this kind of thinking.

Perhaps we should call it the "F# with Mono" guide.

The Microsoft F# .NET Core docs are much better in this regard

**Pull request merged**
