### PR TITLE
please add Bossart Analytics - Functional Software F# Training

### PR DESCRIPTION
**Pull request by FunctionalSoftware**

### CODE REVIEW

**Comment by forki** [comment]
Since the whole site is in english I think you should translate this into english

**Comment by FunctionalSoftware** [comment]
ok translated to english

**Comment by FunctionalSoftware** [comment]
how to resolve an "Unresolved conversation" ? 
How can we speed up the process?

**Comment by forki** [comment]
@dsyme @tpetricek this seems to be ready to merge

**Comment by tpetricek** [comment]
Sorry for the delay. Merged now.

**Comment by FunctionalSoftware** [comment]
Thank you!

**Pull request merged**
