### PR TITLE
[Ideas - don't merge]: Overhaul primary wording/messaging

### PR DESCRIPTION
**Pull request by cartermp**
Looks like this. The point here is more to offer a proposal for how positioning & messaging can change. I didn't really do any styling other than some really bare-bones stuff.

image

### CODE REVIEW

**Comment by bengobeil** [comment]
I like the topics that are selected.

I am looking at other languages (Rust, Kotlin, F#, Scala, etc.) and they all market themselves similarly:

Productive, reliable, cross-platform...

I am wondering how F# can market itself to be distinguished from others.

**Comment by lfr** [comment]
> I am wondering how F# can market itself to be distinguished from others.

I'm glad you brought this up. As I briefly mentioned in the call, one way we can distinguish ourselves is by avoiding marketing terms, in fact this is something that we should do even if we weren't looking to distinguish ourselves.

The landing page real estate is extremely precious and most people will spend less than 30 seconds unless something really grabs their attention, for this reason we need to be picky about what we put in there. Marketing terms are very unlikely to grab anyone's attention simply because we're over-exposed to them.

Qualifiers that are up for interpretation such as "safe", "robust", "performant" don't carry as much weight as factual statements such as "static typing", "functional first", etc, because the latter can't be made up. Since we have to be picky, the former should either only be used to highlight the latter, or perhaps next to code that illustrates it, or otherwise used extremely sparingly.

**Comment by lfr** [comment]
> Looks like this. The point here is more to offer a proposal for how positioning & messaging can change. I didn't really do any styling other than some really bare-bones stuff.

Like @bengobeil I like the choice of topics, I'll try to give more feedback perhaps later in the day.

**Comment by lfr** [comment]
Here's some additional feedback, this is not meant as a replacement of Ben's split logo suggestion on twitter, but rather as food for thought regarding what callouts we may want to put in front of a visitor.

image

**Comment by dsyme** [comment]
Closing this out, some changes have been applied and we can iterate further from here

**Pull request closed without merging**
