### PR TITLE
Added Learning F#: A Case study with branch and bound to the learn page

### PR DESCRIPTION
**Pull request by dlr2**
Added a new F# tutorial, "Learning F#: Case study with branch and bound"

### CODE REVIEW

**Comment by dsyme** [comment]
This entry doesn't seem right as a primary "learn" resource for fsharp.org, though it's great content!

**Comment by dlr2** [comment]
Thanks for the comment. If there's another place for it feel free to link
it there.
Best
Dave

**Comment by dsyme** [comment]
@dlr2 I'm not really sure.  There's no direct place on http://fsharp.org to curate quality-but-non-canonical learning material, except perhaps the "guides".  But this doesn't fit directly into any specific guide.

@tpetricek What do you think?  Where is the place to surface this kind of material - on fsharp.org or elsewhere?  Or do we just let Google find it?

**Comment by dsyme** [comment]
@tpetricek I took a quick look and the material and code is extensive and the teaching well structured for this content.  

@dlr2 Did you have a particular audience in mind when you developed this?  e.g. teaching?

**Comment by dlr2** [comment]
I was thinking of someone coming from an imperative background (almost
everyone) as they move to a functional style. There are lots of tutorials
and snippets on F# of course :-) but I never found anything like this --
where the programming paradigm and process is moved from imperative to
functional in a step by step way.

Even though I did not do the process exactly as I wrote it, I thought that
this would help others. Rather than just show, hey here is branch and bound
in functional form, show how to take a 'standard' (non-trivial) algorithm
and transform it's style. I did not integrate the testing parts in the
development process, even though this is how you would do it, since I
didn't want to distract from the process's 'march' from imperative to
functional.

Yes, I am a teacher too, and I could see how something like this could be
useful. :-) I wanted not just a snippet with explanation but a complete
solution.

fyi; it is linked on FsCheck:
https://fscheck.github.io/FsCheck/LearningResources.html

**Pull request closed without merging**
