### PR TITLE
added Npgsql.FSharp, Donald and SqlHydra

### PR DESCRIPTION
**Pull request by JordanMarr**

### CODE REVIEW

**Review by vzarytovskii — APPROVED** [review]

**Review by dsyme — APPROVED** [review]
I took the opportunity to fix some other things on the page

**Comment by JordanMarr** [comment]
> worth nothing that this one only works on .net framework.

Are you referring to Rezoom.SQL?

**Comment by baronfel** [comment]
yep! though on further reading there appears to be a `standard` branch exploring that support?

**Comment by JordanMarr** [comment]
It looks like it works but has an [open issue](https://github.com/rspeele/Rezoom.SQL/issues/54) related to standard. 🤔
Not sure if that's a big deal or not. 

TBH, I had given up on this library a long time ago because it didn't appear to be active and I didn't want that hassle in my development castle. But it is a very impressive example of a type provider!

**Pull request merged**
