### PR TITLE
Include Forge in Cross Platform Tooling

### PR DESCRIPTION
**Pull request by sideshowcoder**
Copying and managing fsproj files by hand does not work very well in
practice, so I think recommending forge is a reasonable alternative for
now, until dotnet cli becomes the way to go.

### CODE REVIEW

**Comment by dsyme** [comment]
Great. But please keep a short section on editing by hand, and perhaps a small sample of a minimal .fsproj. Also maybe add a link to the guide on FSharp.Core which has samples of different targets

**Comment by dsyme** [comment]
@sideshowcoder I'm thinking this section: http://fsharp.github.io/2015/04/18/fsharp-core-notes.html#examples-of-how-project-files-reference-fsharpcore-and-the-f-targets-file

**Comment by sideshowcoder** [comment]
Definitly good, I'm gonna add a link and add back the section about editing by hand.

**Comment by dsyme** [comment]
Thanks!

**Pull request merged**
