### PR TITLE
Update to the current state (Feb2018)

### PR DESCRIPTION
**Pull request by ShalokShalom**
1) I put the JetBrains option as the first choice, since its cross-platform and follows the spirit of .NET Core and F# by that.
2) Changed the typo "iOS" into "Android"
3) Removed Xamarin Studio, since it is ditched in favour of Visual Studio exclusively.

### CODE REVIEW

**Comment by dsyme** [comment]
@ShalokShalom  Thanks, I accepted the PR  and adjusted terminology a little.   Re top position - I think we should probably rotate top-listed choices across all the different /use/... guides from time to time (or automatically choose randomly) - there are pros and cons of various options and many are evolving.  For Android/iOS, hopefully development choices using VS Code and other editor will also become possible at some point.

BTW I think we also need more content on Fable + React Native here - @forki @alfonsogarciacaro do you have anything you could add?

best
don

**Comment by ShalokShalom** [comment]
I also see QML as a huge option, to be honest is this technique heavily underrated IMHO. 
Fable can produce Javascript, which is a first class citizen and can even get compiled into [C++](http://doc.qt.io/QtQuickCompiler/)

Plus, you can even design the interface without any coding at all. 
See also my issues at [Elixirscript](https://github.com/elixirscript/elixirscript/issues/340) and [Elm](https://github.com/elm-lang/elm-lang.org/issues/738) 

The key is essentially that no coding at all is required from your side, since QML documents simply import .js files, while you can of course make this whole progress a bit more integrated as well. 

The whole thing is hardware accelerated and so on. 

Hope you see the potential, where others fail to. ;)

**Comment by alfonsogarciacaro** [comment]
I should be possible to use Fable with most of the technologies that use JS for mobile development, I had some experiments with React Native and Fuse. However my problem is I'm not doing mobile development at the moment and that's why I'm reluctant to promote Fable for that purpose as people would expect some kind of support I cannot give at the moment.

It'd be fantastic if someone who's using Fable for mobile development could write some template or starter's guide. I would of course provide as much support and guidance as I can on the compiler side.

**Comment by ShalokShalom** [comment]
You can simply use the QML documentation.

**Pull request merged**
