### PR TITLE
Clean up broken installation methods

### PR DESCRIPTION
**Pull request by cnd**
blocker issue: https://github.com/fsharp/fsharp/issues/889

### CODE REVIEW

**Comment by cnd** [comment]
@ninjarobot I can't find msbuild in mono package (but let keep discussion on blocker issue)

**Comment by lenadroid** [comment]
@ninjarobot do you think we can add a note based on the latest @cnd's comment? /cc @ReedCopsey

**Comment by cnd** [comment]
@ninjarobot no, you should rewrite install from sources for rhel and debian too and specify which binary packages users should install (with bundled msbuild) and remove build mono from source part

**Comment by voronoipotato** [comment]
I just installed .net core on fedora the other day, so perhaps I can look at `dnf history` and my bash history to see what steps I needed to take.

**Comment by dsyme** [comment]
Closing as this has been re-written

**Pull request closed without merging**
